/* ============================================================
   Year photo gallery + lightbox (photos.html).
   Reads window.LAB_YEAR_PHOTOS (js/year-photos-data.js, generated by
   scripts/build-year-photos.py). Pure DOM, no dependencies.
   Include AFTER the data file.
   ============================================================ */
(function () {
  "use strict";

  var years = window.LAB_YEAR_PHOTOS || [];
  var gallery = document.getElementById("yearGallery");
  var chipBar = document.getElementById("yearChips");
  if (!gallery || !years.length) return;

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  /* flat list so the lightbox can run straight through the whole album */
  var all = [];
  years.forEach(function (y) {
    y.photos.forEach(function (p, i) {
      all.push({ i: all.length, year: y.year, index: i, count: y.photos.length, photo: p });
    });
  });

  function altFor(item) {
    return item.photo.caption || "Lab photo, " + item.year;
  }
  function hashFor(item) {
    return item.year + "-" + (item.index + 1);
  }

  /* ---------- grid ---------- */
  chipBar.innerHTML =
    '<div class="wrap">' +
    years.map(function (y) {
      return '<a class="year-chip" href="#y' + y.year + '">' + y.year + "</a>";
    }).join("") +
    "</div>";

  var flat = 0;
  gallery.innerHTML = years.map(function (y) {
    var n = y.photos.length;
    var cells = y.photos.map(function (p, i) {
      var item = all[flat++];
      return '<button class="yp-item" type="button" data-i="' + item.i + '">' +
        '<img src="' + esc(p.thumb) + '" alt="' + esc(altFor(item)) + '" loading="lazy" decoding="async">' +
        (p.caption ? '<span class="yp-cap">' + esc(p.caption) + "</span>" : "") +
        "</button>";
    });
    return '<section class="yp-year" id="y' + y.year + '">' +
      '<div class="pub-year">' + y.year + ' <span class="yp-count">' + n +
      (n === 1 ? " photo" : " photos") + "</span></div>" +
      '<div class="yp-grid">' + cells.join("") + "</div></section>";
  }).join("");

  var tiles = gallery.querySelectorAll(".yp-item");

  /* ---------- lightbox ---------- */
  var box = document.createElement("dialog");
  box.className = "lightbox";
  box.innerHTML =
    '<figure class="lb-stage">' +
    '<img id="lbImg" alt="">' +
    '<figcaption class="lb-meta"><span class="lb-where" id="lbWhere"></span>' +
    '<span class="lb-cap" id="lbCap"></span></figcaption></figure>' +
    '<button class="lb-btn lb-prev" type="button" aria-label="Previous photo">‹</button>' +
    '<button class="lb-btn lb-next" type="button" aria-label="Next photo">›</button>' +
    '<button class="lb-btn lb-close" type="button" aria-label="Close">×</button>';
  document.body.appendChild(box);

  var lbImg = box.querySelector("#lbImg");
  var lbWhere = box.querySelector("#lbWhere");
  var lbCap = box.querySelector("#lbCap");
  var current = -1;
  var opener = null;

  function preload(i) {
    var item = all[i];
    if (item) new Image().src = item.photo.src;
  }

  function show(i) {
    if (i < 0) i = all.length - 1;
    if (i >= all.length) i = 0;
    current = i;
    var item = all[i];
    lbImg.src = item.photo.src;
    lbImg.alt = altFor(item);
    lbImg.width = item.photo.w;
    lbImg.height = item.photo.h;
    lbWhere.textContent = item.year + " · " + (item.index + 1) + " / " + item.count;
    lbCap.textContent = item.photo.caption || "";
    setHash(hashFor(item));
    preload(i + 1);
    preload(i - 1);
  }

  var suppressHash = false;
  function setHash(h) {
    suppressHash = true;
    history.replaceState(null, "", "#" + h);
    suppressHash = false;
  }

  function open(i, fromEl) {
    opener = fromEl || null;
    show(i);
    if (typeof box.showModal === "function") box.showModal();
    else box.setAttribute("open", "");
    document.body.classList.add("lb-open");
  }

  function close() {
    if (typeof box.close === "function") box.close();
    else box.removeAttribute("open");
  }

  box.addEventListener("close", function () {
    document.body.classList.remove("lb-open");
    lbImg.removeAttribute("src");
    var item = all[current];
    if (item) setHash("y" + item.year);
    if (opener) { opener.focus(); opener = null; }
  });

  tiles.forEach(function (btn) {
    btn.addEventListener("click", function () {
      open(Number(btn.getAttribute("data-i")), btn);
    });
  });

  box.querySelector(".lb-prev").addEventListener("click", function () { show(current - 1); });
  box.querySelector(".lb-next").addEventListener("click", function () { show(current + 1); });
  box.querySelector(".lb-close").addEventListener("click", close);

  box.addEventListener("keydown", function (e) {
    if (e.key === "ArrowLeft") { e.preventDefault(); show(current - 1); }
    else if (e.key === "ArrowRight") { e.preventDefault(); show(current + 1); }
    else if (e.key === "Escape") { close(); }  // modal <dialog> does this itself; covers the fallback
  });

  /* click outside the photo closes (the dialog element fills the viewport) */
  box.addEventListener("click", function (e) {
    if (!e.target.closest(".lb-stage") && !e.target.closest(".lb-btn")) close();
  });

  /* swipe */
  var touchX = null, touchY = null;
  box.addEventListener("touchstart", function (e) {
    touchX = e.changedTouches[0].clientX;
    touchY = e.changedTouches[0].clientY;
  }, { passive: true });
  box.addEventListener("touchend", function (e) {
    if (touchX === null) return;
    var dx = e.changedTouches[0].clientX - touchX;
    var dy = e.changedTouches[0].clientY - touchY;
    touchX = null;
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) show(current + (dx < 0 ? 1 : -1));
  }, { passive: true });

  /* ---------- deep links: #2019-3 opens that photo ---------- */
  function openFromHash() {
    if (suppressHash) return;
    var m = /^#(\d{4})-(\d+)$/.exec(location.hash);
    if (!m) return;
    for (var i = 0; i < all.length; i++) {
      if (all[i].year === Number(m[1]) && all[i].index === Number(m[2]) - 1) {
        var tile = tiles[i];
        if (tile) tile.scrollIntoView({ block: "center" });
        open(i, tile);
        return;
      }
    }
  }
  window.addEventListener("hashchange", openFromHash);
  openFromHash();
})();
