#!/usr/bin/env python3
# Regenerate js/people-data.js (LAB_PEOPLE, drives the People timeline).
#
# Source of truth, in priority order:
#   1. data/people-roster.xlsx  — the fillable roster Ed & Sara maintain
#   2. data/people.tsv          — tab-separated fallback (from build_people.py)
#
# Usage (from repo root):
#   python3 scripts/generate-people.py
#
# Columns (header row, case-insensitive):
#   name, role, start_year, end_year, current_position, website, linkedin
# role: pi | postdoc | grad | staff | undergrad | visiting
# end_year: a 4-digit year or "present" (blank = present)
# People with a blank start_year can't be placed on the timeline; they're
# skipped and listed so you can backfill their years.
import csv, os

XLSX = 'data/people-roster.xlsx'
TSV = 'data/people.tsv'
OUT = 'js/people-data.js'
VALID_ROLES = {'pi', 'postdoc', 'grad', 'staff', 'undergrad', 'visiting'}
FIELDS = ['name', 'role', 'start_year', 'end_year', 'current_position', 'website', 'linkedin']


def rows_from_xlsx(path):
    from openpyxl import load_workbook
    wb = load_workbook(path, data_only=True)
    ws = wb['Roster'] if 'Roster' in wb.sheetnames else wb.active
    it = ws.iter_rows(values_only=True)
    # normalize pretty labels ("Start year") to machine fields ("start_year")
    header = [str(h).strip().lower().replace(' ', '_') if h is not None else '' for h in next(it)]
    idx = {f: (header.index(f) if f in header else None) for f in FIELDS}
    out = []
    for row in it:
        def g(f):
            i = idx[f]
            return '' if i is None or i >= len(row) or row[i] is None else str(row[i]).strip()
        if not g('name'):
            continue
        out.append({f: g(f) for f in FIELDS})
    return out


def rows_from_tsv(path):
    out = []
    for r in csv.DictReader(open(path, encoding='utf-8'), delimiter='\t'):
        out.append({f: (r.get(f) or '').strip() for f in FIELDS})
    return out


src = XLSX if os.path.exists(XLSX) else TSV
rows = rows_from_xlsx(XLSX) if src == XLSX else rows_from_tsv(TSV)

people, skipped = [], []
for r in rows:
    name, start = r['name'], r['start_year']
    if not start.replace('.0', '').isdigit():
        skipped.append(name)
        continue
    role = r['role'].lower()
    if role not in VALID_ROLES:
        role = 'staff'
    end_raw = r['end_year'].lower().replace('.0', '')
    end = 'present' if end_raw in ('', 'present') else (int(end_raw) if end_raw.isdigit() else 'present')
    people.append({
        'name': name, 'role': role, 'start': int(start.replace('.0', '')), 'end': end,
        'now': r['current_position'], 'site': r['website'], 'linkedin': r['linkedin'],
    })

people.sort(key=lambda p: (p['start'], p['name']))


def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


lines = []
for p in people:
    parts = ["name:'%s'" % esc(p['name']), "role:'%s'" % p['role'], "start:%d" % p['start']]
    parts.append("end:'present'" if p['end'] == 'present' else "end:%d" % p['end'])
    if p['now']:
        parts.append("now:'%s'" % esc(p['now']))
    if p['site']:
        parts.append("site:'%s'" % esc(p['site']))
    if p['linkedin']:
        parts.append("linkedin:'%s'" % esc(p['linkedin']))
    lines.append('  { ' + ', '.join(parts) + ' }')

header = '''/* ============================================================
   People data — drives the "lab over time" timeline on people.html.
   Rendered by js/lab-archive.js (renderPeopleTimeline).

   GENERATED by scripts/generate-people.py from data/people-roster.xlsx
   (fillable roster Ed & Sara maintain) or data/people.tsv — do not hand-edit.

   Schema: { name, role(pi|postdoc|grad|staff|undergrad|visiting),
             start (year), end (year|"present"),
             now (optional), site (optional URL), linkedin (optional URL) }
   ============================================================ */

'''
open(OUT, 'w', encoding='utf-8').write(header + 'window.LAB_PEOPLE = [\n' + ',\n'.join(lines) + '\n];\n')
print('Source: %s' % src)
print('Wrote %d people to %s (skipped %d with no start year)' % (len(people), OUT, len(skipped)))
if skipped:
    print('Needs years:', ', '.join(sorted(skipped)))
