#!/usr/bin/env python3
# Regenerate the People data files from the roster Ed & Sara maintain.
#
#   data/people-roster.xlsx  ->  js/people-data.js     (window.LAB_PEOPLE)
#                                js/profiles-data.js    (window.LAB_PROFILES)
#
# LAB_PEOPLE drives the "lab over time" timeline (people with a start year).
# LAB_PROFILES drives the per-person profile pages (person.html) — every
# member with a bio or photo, keyed by a name slug, including those without
# years (undergrads, short-term visitors).
#
# Usage (from repo root):  python3 scripts/generate-people.py
#
# Columns (header row, case-insensitive; pretty labels like "Start year" ok):
#   name, role, start_year, end_year, current_position, website, linkedin,
#   title, bio, email, scholar, orcid, twitter, photo
import csv, os, re, json

XLSX = 'data/people-roster.xlsx'
TSV = 'data/people.tsv'
OUT_PEOPLE = 'js/people-data.js'
OUT_PROFILES = 'js/profiles-data.js'
VALID_ROLES = {'pi', 'postdoc', 'grad', 'staff', 'undergrad', 'visiting'}
FIELDS = ['name', 'role', 'start_year', 'end_year', 'current_position', 'website',
          'linkedin', 'title', 'bio', 'email', 'scholar', 'orcid', 'twitter', 'photo']


def slugify(s):
    return re.sub(r'^-|-$', '', re.sub(r'[^a-z0-9]+', '-', (s or '').lower()))


def rows_from_xlsx(path):
    from openpyxl import load_workbook
    wb = load_workbook(path, data_only=True)
    ws = wb['Roster'] if 'Roster' in wb.sheetnames else wb.active
    it = ws.iter_rows(values_only=True)
    header = [str(h).strip().lower().replace(' ', '_') if h is not None else '' for h in next(it)]
    idx = {f: (header.index(f) if f in header else None) for f in FIELDS}
    out = []
    for row in it:
        def g(f):
            i = idx[f]
            return '' if i is None or i >= len(row) or row[i] is None else str(row[i]).strip()
        if not g('name'):
            continue
        out.append({f: g(f) for f in FIELDS})
    return out


def rows_from_tsv(path):
    return [{f: (r.get(f) or '').strip() for f in FIELDS}
            for r in csv.DictReader(open(path, encoding='utf-8'), delimiter='\t')]


src = XLSX if os.path.exists(XLSX) else TSV
rows = rows_from_xlsx(XLSX) if src == XLSX else rows_from_tsv(TSV)


def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


# ---- LAB_PEOPLE (timeline: people with a start year) ----
people, skipped = [], []
for r in rows:
    name, start = r['name'], r['start_year']
    slug = slugify(name)
    if not start.replace('.0', '').isdigit():
        skipped.append(name)
        continue
    role = r['role'].lower()
    if role not in VALID_ROLES:
        role = 'staff'
    end_raw = r['end_year'].lower().replace('.0', '')
    end = 'present' if end_raw in ('', 'present') else (int(end_raw) if end_raw.isdigit() else 'present')
    people.append({'name': name, 'slug': slug, 'role': role,
                   'start': int(start.replace('.0', '')), 'end': end,
                   'now': r['current_position'], 'site': r['website'],
                   'linkedin': r['linkedin'], 'photo': r['photo']})
people.sort(key=lambda p: (p['start'], p['name']))

lines = []
for p in people:
    parts = ["name:'%s'" % esc(p['name']), "slug:'%s'" % p['slug'],
             "role:'%s'" % p['role'], "start:%d" % p['start']]
    parts.append("end:'present'" if p['end'] == 'present' else "end:%d" % p['end'])
    if p['now']:
        parts.append("now:'%s'" % esc(p['now']))
    if p['site']:
        parts.append("site:'%s'" % esc(p['site']))
    if p['linkedin']:
        parts.append("linkedin:'%s'" % esc(p['linkedin']))
    if p['photo']:
        parts.append("photo:'%s'" % esc(p['photo']))
    lines.append('  { ' + ', '.join(parts) + ' }')

people_hdr = '''/* ============================================================
   People data — drives the "lab over time" timeline on people.html.
   GENERATED by scripts/generate-people.py from data/people-roster.xlsx.
   Schema: { name, slug, role, start, end(year|"present"),
             now?, site?, linkedin?, photo? }
   ============================================================ */

'''
open(OUT_PEOPLE, 'w', encoding='utf-8').write(
    people_hdr + 'window.LAB_PEOPLE = [\n' + ',\n'.join(lines) + '\n];\n')


# ---- LAB_PROFILES (profile pages: everyone with a bio or photo) ----
profiles = {}
for r in rows:
    if not (r['bio'] or r['photo']):
        continue
    slug = slugify(r['name'])
    role = r['role'].lower()
    if role not in VALID_ROLES:
        role = 'staff'
    start = r['start_year'].replace('.0', '')
    end = r['end_year'].replace('.0', '')
    rec = {'name': r['name'], 'role': role}
    for k in ('title', 'bio', 'email', 'scholar', 'orcid', 'twitter', 'photo'):
        if r[k]:
            rec[k] = r[k]
    if r['website']:
        rec['website'] = r['website']
    if r['linkedin']:
        rec['linkedin'] = r['linkedin']
    if r['current_position']:
        rec['now'] = r['current_position']
    if start.isdigit():
        rec['start'] = int(start)
    if end.isdigit():
        rec['end'] = int(end)
    elif start.isdigit() and end.lower() in ('', 'present'):
        rec['end'] = 'present'
    profiles[slug] = rec

profiles_hdr = '''/* ============================================================
   Per-person profile data — drives person.html (renderProfile).
   GENERATED by scripts/generate-people.py from data/people-roster.xlsx.
   Keyed by name slug; bios/photos migrated from the old Wix site.
   ============================================================ */

'''
open(OUT_PROFILES, 'w', encoding='utf-8').write(
    profiles_hdr + 'window.LAB_PROFILES = ' +
    json.dumps(profiles, ensure_ascii=False, indent=1) + ';\n')

print('Source: %s' % src)
print('Wrote %d people to %s (skipped %d with no start year)' % (len(people), OUT_PEOPLE, len(skipped)))
print('Wrote %d profiles to %s' % (len(profiles), OUT_PROFILES))
